# Generated by Django 4.2 on 2023-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mark',
            field=models.CharField(choices=[(1, '1'), (2, '2')], default=0, max_length=10),
        ),
    ]
