# Generated by Django 4.2 on 2023-05-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_mark_postmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mark',
        ),
    ]
