# Generated by Django 4.2 on 2023-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_rename_body_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmark',
            name='mark',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10),
        ),
    ]
